### ISSUE TITLE
Access My List

### ISSUE THREAD

**Issue by lloyda** [dimkroon/itvx-for-kodi#14]
If I use the ITVX app on my phone, I can create a list of shows to watch later.  Would it be possible to access this via your plug-in?

**Comment by dimkroon** [comment]
Thanks for your suggestion @lloyda.
It's funny you mentioning creating a list with the official app, because all my attempts to do so failed. It does work on the website however, so it should be possible. 
Implementation will take some time though and any work on user account features like this is planned after the release of version 1.0

**Comment by lloyda** [comment]
Thanks.  Interesting comment about your app issues.  For info, I'm using Android v11.4.0

**Comment by dimkroon** [comment]
@lloyda 
A first attempt of implementing 'My List' is available in the branch feature_user_my_list. If you like you can clone the branch and copy the folder plugin.video.itvhub to thye addons folder of you Kodi setup, over the existing addon. Or zip plugin.video.itvhub and do a zip install.
I am very interested to hear if this works for you and feel free to comment on the feature in any way you like.

**Comment by lloyda** [comment]
Initial test looks promising.  It picked up the items that were on the list I created on the mobile app.  I'll do some more in depth testing when  I get a chance.

**Comment by lloyda** [comment]
I have found one potential oddity.  It is not a big deal but thought I should still mention it.

If you add something to the list, which has a number of series, you get a structure which is a folder containing folders for each series.  The Options for each series allows that series to be added the the list, which I think is odd, as it is already in the list.  You can create an example with Doc Marten.

Apart from that, seems great.

**Comment by dimkroon** [comment]
Thanks for testing @lloyda. Yes, I agree it's a little odd and certainly worth mentioning. 

When a programme from 'My List' is a folder, i.e. when it is not a playable item, the listing shown when you selected the programme is in fact exactly the same as the one shown when you navigate to the same programme via collections or categories. If you take that route you can also add a programme that is already on 'My List'. 

It's is quite easy to simply not present the 'Add to My List' context menu option on items displayed via 'My List', but that doesn't address the oddity in category and collections. It would be much more elegant to check in every listing if a programme is already on 'My List' and adjust the context menu accordingly. 

Anyway, it doesn't cause problems, since itv never shows the same programme more than once in 'My List', however often it's been added. 
But I don't like oddities, so I'll keep this issue open until I've decided what to do.

**Comment by ickam** [comment]
I have a related request. Is it possible for this addon to recognise played episodes? 

When we watch the Chase, no matter if we start from the top or bottom on the app, it doesn't reliably play the next episode, but often a random one. I was hoping to use your addon instead, but we got through quite a lot of episodes already

**Comment by dimkroon** [comment]
This is a different feature than mylist.

Kodi itself automatically stores the played stated of episodes and marked with a 'V' if completely played or a half circle if partly played. However, if data, like the name of the episode changes Kodi doesn't recognise the item and it's status is 'not watched'.
I see no point in implementing something similar in the addon.

Regarding the Chase:
Since most episode are repeats, I wonder if there is such a thing as the real next episode. When I watch the chase I prefer to sort the listing of episodes on 'Date' which lists in order of last broadcast. Maybe that makes finding the next episode a bit easier.

There is a feature 'Continue Watching" on the app that presents the next episode. If that gets implemented in the addon it will obtain the same data from ITVX as the app or website does. I know of no other I way to obtain played status of episodes.

Please open a new issue if you want to continue the discussion.

**Comment by dimkroon** [comment]
So I think I finally got it sorted.

@lloyda
If you are still interested, check out https://github.com/dimkroon/itvx-for-kodi/tree/4978fc6e6a9403df3b704fe47ad36c442706fdcd and give it a try.

There's still one peculiarity left though; on saved search terms all it's OK, but when an item is added from search results of a new search, the keyboard to enter a search term is shown again. Right now, I have absolutely no idea how and this can be prevented. Maybe I'll end up removing My List context menu option on search result all together, but I think search results are just so particularly suited to being added to My List. I'll keep it in for now until I've decided, which can easily take another 9 months....

**Comment by dimkroon** [comment]
I decided to just not refresh the list of results after adding/removing a search results to/from My List the list. 
That means that if a user adds a search result and immediately afterwards opens the context menu of that item again, there will still be the option to add the item to My List, instead of remove. I',m afraid that will be a slight peculiarity that remains. 
My List is now in development and will be in the upcoming version 1.2.0
