### ISSUE TITLE
Login timed out

### ISSUE THREAD

**Issue by jaca2300** [dimkroon/itvx-for-kodi#82]
Hi

I get an error like: "Login timed out ssl itv.com:443".
Then I restart Kodi, sometime 2 or 3 times until I don't get the error and can use the addon again.
I can't find anything in kodi.log
But I think it is something like in https://pastebin.com/8piXaVZs
Where do I turn on logging in viwx? Or where can I find the log?
Are there anywhere I can increase the login response time (to avoid  timeout)?
I'm using VPN to London, UK, from abroad. But the Tunnel is ok, and I can use ITV.com in a chromium-browser whiteout any problem.

**Comment by jaca2300** [comment]
Think I solved it by making a runnable file in `/etc/network/if-up.d/` containing:
```
#!/bin/sh
if [ "$IFACE" = "tun0" ]; then
    ping -c 2 -R itv.com >/root/ping.log
fi
```
To secure the route to itv.com when tun0 (my VPN-tunnel) is up.

But would still like to know how to watch the viwx log

Best Regards

Jacob

**Comment by jaca2300** [comment]
No that didn't solve it.
The error is:
```
FetchError
HTTPSConnectionPool(host='www.itv.com'; port=443): Max retries exceeded with url: /(Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF)(_ssl.c:992)'
```
Hope you got a solutin.

Best regards

Jacob

**Comment by dimkroon** [comment]
Seems like you've managed to keep yourself busy this afternoon ;-)

ViwX's settings has a section concerning logging. By default viwx logs to the Kodi log. That is the preferred way of logging, since the Kodi log contains invaluable info regarding your system and shows viwX's log entries in relation to other things happening on your system. Ensure that 'log to' is set to 'Kodi Log' and that log level is 'Debug'. 

In order to allow logging from viwX (and other plugins) to enter the Kodi log, debug logging must be enabled in Kodi's settings. Check https://kodi.wiki/view/Log_file for more info. 

If signing in to ITVX times out, try to open the viwX addon in Kodi and check if listing category or collection works. You did well by trying to use a web browser, but did you do exactly the same in the browser? i.e. if signing in fails in viwX, did you try to actually sign in using the web browser? It wouldn't be the first time that ITV messes something up.

> Are there anywhere I can increase the login response time (to avoid timeout)?

Time-outs are defined by the 'constant' WEB_TIMEOUT in module fetch.py. If connections time out with these setting there is usually another problem. If increasing time-outs has a positive effect it is most likely only masking this issue, rather than solving it.

> Hope you got a solutin.

Well, there is very little info to go. It very much looks like a network issue, though. I don't apply the same strict rules as the kodi forum, but I'm afraid I can't help you get illegal access to ITVX. If you are confident that network is not an issue, please describe as exact and in as much detail as possible what you were doing, in what order, and what messages you see where. And post (a link to) a full debug log.

**Comment by dimkroon** [comment]
Closing down now, since there's no response.
